# -*- coding: utf-8 -*-
"""Generate docs/doc-lang-map.js from hreflang pairs in HTML."""
from pathlib import Path
import re
import json

ROOT = Path(__file__).resolve().parents[1]
docs = ROOT / "docs"
OUT = docs / "doc-lang-map.js"

href_re = re.compile(
    r'href="([^"]+)"[^>]*hreflang="(en|de)"|hreflang="(en|de)"[^>]*href="([^"]+)"',
    re.I,
)
lang_re = re.compile(r'<html[^>]*\slang="(en|de)"', re.I)

pairs = {}
for p in docs.rglob("*.html"):
    t = p.read_text(encoding="utf-8", errors="ignore")
    m = lang_re.search(t)
    if not m:
        continue
    lang = m.group(1).lower()
    for hm in href_re.finditer(t):
        href = hm.group(1) or hm.group(4)
        target_lang = (hm.group(2) or hm.group(3)).lower()
        if not href or href.startswith(("http", "#", "mailto:")):
            continue
        other = (p.parent / href.split("#")[0]).resolve()
        try:
            other_rel = other.relative_to(docs.resolve()).as_posix()
        except ValueError:
            continue
        if not other.is_file():
            continue
        self_rel = p.relative_to(docs).as_posix()
        if {lang, target_lang} == {"en", "de"}:
            pairs[self_rel] = other_rel
            pairs[other_rel] = self_rel

en_to_de = {}
for src, dst in sorted(pairs.items()):
    head = (docs / src).read_text(encoding="utf-8", errors="ignore")[:800]
    lm = lang_re.search(head)
    if lm and lm.group(1).lower() == "en":
        en_to_de[src] = dst

body = json.dumps(en_to_de, indent=2, ensure_ascii=False)
OUT.write_text(
    "/* Auto-generated by tools/gen-doc-lang-map.py — do not edit */\n"
    "window.__VELIN_DOC_LANG__ = {\n"
    "  enHub: 'getting-started/introduction.html',\n"
    "  deHub: 'getting-started/einfuehrung.html',\n"
    f"  enToDe: {body}\n"
    "};\n",
    encoding="utf-8",
)
print(f"Wrote {OUT} ({len(en_to_de)} EN->DE pairs)")
