#!/usr/bin/env python3
"""Document VelinStyle 0.9.0 audit follow-up in velinstyle-site/docs."""
from __future__ import annotations

import re
import shutil
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
FRAMEWORK = SITE.parent / "velinstyle"
DOCS = SITE / "docs"


def patch_file(rel: str, *subs: tuple[str, str]) -> None:
    path = DOCS / rel
    text = path.read_text(encoding="utf-8")
    orig = text
    for old, new in subs:
        if old not in text:
            continue
        text = text.replace(old, new, 1)
    if text != orig:
        path.write_text(text, encoding="utf-8")
        print(f"patched {rel}")


def main() -> None:
    # Changelog highlights
    patch_file(
        "changelog.html",
        (
            '        <li><strong>Unreleased / 0.9.0 extension</strong> — Velin-Meta, VelinSearch, motion, highlight, attributes, docs generate, PII scanner.</li>',
            '        <li><strong>Unreleased / 0.9.0 extension</strong> — Velin-Meta, VelinSearch, motion, highlight, attributes, docs generate, PII scanner.</li>\n'
            '        <li><strong>Audit follow-up (framework)</strong> — <code>velin-scroll-top</code> declarative attribute; '
            '<code>wc-placeholder.css</code> CLS guards; <code>velin-persist</code> in component contracts (36/36); '
            'Playwright cross-browser smoke (<code>npm run test:e2e</code>); harmonized <code>velin-agent.json</code>.</li>\n'
            '        <li><strong><a href="https://github.com/SkyliteDesign/velinstyle/releases/tag/v0.9.0">0.9.0</a></strong> — Runtime modules, security fixes, WCAG 2.2, token validate, perf audit.</li>',
        ),
    )

    # Sync framework CHANGELOG
    src_cl = FRAMEWORK / "CHANGELOG.md"
    dst_cl = DOCS / "CHANGELOG.md"
    if src_cl.is_file():
        shutil.copy2(src_cl, dst_cl)
        print("copied CHANGELOG.md")

    # HTML attributes
    patch_file(
        "guides/html-attributes.html",
        (
            '      <p><code>bootAttributes()</code> scans for registered attribute names, runs <code>enhance(el)</code> once per element, then <code>initMotion()</code>. Register custom handlers with <code>registerAttribute(name, &#123; enhance &#125;)</code>.</p>',
            '      <p><code>bootAttributes()</code> scans for registered attribute names, runs <code>enhance(el)</code> once per element, then <code>initMotion()</code> and ensures a global <code>&lt;velin-announcer&gt;</code> when needed. Register custom handlers with <code>registerAttribute(name, &#123; enhance &#125;)</code>. <strong>27 attributes</strong> are built in (see generated reference).</p>',
        ),
        (
            "          <tr><td><code>velin-search</code></td><td><code>&lt;velin-search&gt;</code></td></tr>\n        </tbody>",
            "          <tr><td><code>velin-search</code></td><td><code>&lt;velin-search&gt;</code></td></tr>\n"
            "          <tr><td><code>velin-scroll-top</code></td><td><code>&lt;velin-scroll-top&gt;</code> (threshold from attribute value)</td></tr>\n"
            "        </tbody>",
        ),
        (
            '      <h2 id="generated">Generated docs</h2>\n      <p>Per-attribute Markdown is generated by <code>velinstyle docs generate</code> into <code>docs/generated/attributes/</code>. Sync to this site with <code>npm run sync:generated</code>.</p>',
            '      <h2 id="declarative-scroll-top">Declarative scroll-to-top</h2>\n'
            '      <p>Add <code>velin-scroll-top</code> on <code>&lt;body&gt;</code> or any element — no extra markup. Works with <code>bootFromDOM(document, &#123; attributes: true &#125;)</code>:</p>\n'
            '      <pre><code class="language-html">&lt;body velin-scroll-top="400"&gt;\n  ...\n&lt;/body&gt;</code></pre>\n'
            '      <p>See also <a href="../components/scroll-top.html">Scroll to top component</a>.</p>\n\n'
            '      <h2 id="generated">Generated docs</h2>\n'
            '      <p>Per-attribute Markdown is generated by <code>velinstyle docs generate</code> into <code>docs/generated/attributes/</code> (including <code>velin-scroll-top.md</code>). Sync to this site with <code>npm run sync:generated</code>.</p>',
        ),
        (
            '        <li><a href="#generated">Generated docs</a></li>',
            '        <li><a href="#declarative-scroll-top">Declarative scroll-top</a></li>\n        <li><a href="#generated">Generated docs</a></li>',
        ),
    )

    # Accessibility
    patch_file(
        "getting-started/accessibility.html",
        (
            '        Mounts <code>&lt;velin-announcer&gt;</code> for polite/assertive live regions and sets\n'
            '        <code>scroll-padding-block-start</code> when a <code>.site-nav</code> or\n'
            '        <code>[data-velin-nav]</code> header is present. Guide:\n'
            '        <a href="../getting-started/accessibility.html#a11y-bootstrap">Accessibility</a>.',
            '        Mounts <code>&lt;velin-announcer&gt;</code> for polite/assertive live regions and sets\n'
            '        <code>scroll-padding-block-start</code> when a <code>.site-nav</code> or\n'
            '        <code>[data-velin-nav]</code> header is present. Framework contracts:\n'
            '        <code>core/a11y/component-contracts.json</code> (36 components, all <code>pass</code>).\n'
            '        Run <code>npm run test:a11y:coverage</code> in the framework repo. Guide:\n'
            '        <a href="../getting-started/accessibility.html#a11y-bootstrap">Accessibility</a>.',
        ),
        (
            '      <h2 id="a11y-bootstrap">Runtime bootstrap (<code>initA11y</code>)</h2>',
            '      <h2 id="contracts">Component contracts (36)</h2>\n'
            '      <p>Each shipped web component has an entry in <code>core/a11y/component-contracts.json</code> (status, keyboard, live regions, required attributes). '
            '<code>&lt;velin-persist&gt;</code> supports WCAG 2.2 <strong>3.3.7 Redundant Entry</strong> by auto-saving form fields. '
            'See <a href="../generated/a11y/wcag22-aaa-matrix.md">WCAG 2.2 AAA matrix</a> (six criteria remain <code>partial</code> — author responsibility).</p>\n'
            '      <h2 id="a11y-bootstrap">Runtime bootstrap (<code>initA11y</code>)</h2>',
        ),
    )

    # JavaScript API
    patch_file(
        "extend/javascript-api.html",
        (
            '// 38 lazy-loaded tags (incl. `velin-tooltip`, `velin-stepper` aliases). Subpaths:',
            '// 36 canonical tags + 2 legacy aliases (`velin-tooltip-wc`, `velin-stepper-wc`). Subpaths:',
        ),
        (
            'await bootFromDOM(document, { attributes: true, highlight: true });\n// Full bundle: import \'@birdapi/velinstyle/bundle\';',
            'await bootFromDOM(document, { attributes: true, highlight: true });\n'
            '// Registers all velin-* tags in DOM via COMPONENT_LOADERS (38 entries, deduplicated promises)\n'
            '// Full bundle: import \'@birdapi/velinstyle/bundle\';',
        ),
        (
            '      <h2 id="runtime">Runtime API (0.9.0)</h2>',
            '      <h2 id="runtime">Runtime API (0.9.0)</h2>\n'
            '      <h2 id="runtime-tests">Runtime tests</h2>\n'
            '      <p>In the framework repo: <code>tests/runtime-boot.test.js</code> verifies all loader tags register without race failures; '
            '<code>tests/e2e/wc-smoke.spec.js</code> runs Playwright smoke (Chromium, Firefox, WebKit). Commands: <code>npm test</code>, <code>npm run test:e2e</code>.</p>\n'
            '      <h2 id="runtime">Runtime API (0.9.0)</h2>',
        ),
    )

    # Browser compatibility
    patch_file(
        "getting-started/browser-compatibility.html",
        (
            '      <h2 id="fallbacks">Fallbacks</h2>\n      <p>Use <code>@media (prefers-reduced-motion: reduce)</code> patterns built into animation utilities. Test forced-colors via <a href="accessibility.html">Accessibility</a>.</p>',
            '      <h2 id="e2e">Cross-browser verification (Playwright)</h2>\n'
            '      <p>The framework ships <code>tests/e2e/wc-smoke.spec.js</code> — smoke tests for declarative attributes, '
            '<code>velin-copy</code>, canonical and legacy tooltip/stepper tags. CI runs Chromium, Firefox, and WebKit. '
            'From a checkout of <a href="https://github.com/SkyliteDesign/velinstyle">velinstyle</a>: <code>npm run build && npm run test:e2e</code>.</p>\n'
            '      <h2 id="fallbacks">Fallbacks</h2>\n'
            '      <p>Use <code>@media (prefers-reduced-motion: reduce)</code> patterns built into animation utilities. Test forced-colors via <a href="accessibility.html">Accessibility</a>.</p>',
        ),
        (
            '        <li><a href="#fallbacks">Fallbacks</a></li>',
            '        <li><a href="#e2e">Cross-browser verification</a></li>\n        <li><a href="#fallbacks">Fallbacks</a></li>',
        ),
    )

    # Web components
    patch_file(
        "extend/web-components.html",
        (
            '      <p class="lead">VelinStyle provides 22 native Web Components that enhance standard HTML with interactive behavior — no framework required. All components are XSS-safe with built-in HTML escaping.</p>',
            '      <p class="lead">VelinStyle provides <strong>36 canonical</strong> Web Components (38 lazy-loader entries including legacy <code>velin-tooltip-wc</code> and <code>velin-stepper-wc</code>). All use Shadow DOM or light DOM with XSS-safe escaping where content is dynamic.</p>',
        ),
        (
            '      <p>All components ship with TypeScript definitions and XSS-safe rendering via <code>escapeHTML()</code>.</p>',
            '      <h2 id="cls">Layout stability (CLS)</h2>\n'
            '      <p>Before custom elements upgrade, <code>src/base/wc-placeholder.css</code> reserves min dimensions per display mode '
            '(block, inline, fixed, <code>display:contents</code>) so pages do not shift when scripts load. Included in the main CSS bundle.</p>\n'
            '      <p>All components ship with TypeScript definitions. Import types from <code>dist/velinstyle.d.ts</code>.</p>',
        ),
    )
    wc_path = DOCS / "extend/web-components.html"
    if wc_path.is_file():
        t = wc_path.read_text(encoding="utf-8")
        if '<li><a href="#cls">Layout stability</a></li>' not in t:
            t = t.replace(
                '<li><a href="#components">Component List</a></li><li><a href="#focus">Focus Management</a></li>',
                '<li><a href="#components">Component List</a></li><li><a href="#cls">Layout stability</a></li><li><a href="#focus">Focus Management</a></li>',
                1,
            )
            wc_path.write_text(t, encoding="utf-8")
            print("patched extend/web-components.html (toc)")

    # Scroll top component page
    patch_file(
        "components/scroll-top.html",
        (
            '      <h2 id="basic">Basic</h2>',
            '      <h2 id="declarative">Declarative attribute</h2>\n'
            '      <p>Without a custom element in markup, set <code>velin-scroll-top</code> on <code>&lt;body&gt;</code> (or any element). '
            'Requires <code>bootFromDOM(document, &#123; attributes: true &#125;)</code> or <code>bootAttributes()</code>:</p>\n'
            '      <pre><code class="language-html">&lt;body velin-scroll-top="400"&gt;\n  ...\n&lt;/body&gt;</code></pre>\n'
            '      <p>See <a href="../guides/html-attributes.html#declarative-scroll-top">HTML attributes guide</a>.</p>\n\n'
            '      <h2 id="basic">Basic</h2>',
        ),
    )
    st_path = DOCS / "components/scroll-top.html"
    if st_path.is_file():
        t = st_path.read_text(encoding="utf-8")
        if '<li><a href="#declarative">Declarative attribute</a></li>' not in t:
            t = t.replace(
                '<li><a href="#basic">Basic</a></li><li><a href="#attributes">Attributes</a></li>',
                '<li><a href="#declarative">Declarative attribute</a></li><li><a href="#basic">Basic</a></li><li><a href="#attributes">Attributes</a></li>',
                1,
            )
            st_path.write_text(t, encoding="utf-8")
            print("patched components/scroll-top.html (toc)")

    # Persist
    patch_file(
        "components/persist.html",
        (
            '      <p class="lead">Wrap a form (or any container) with <code>&lt;velin-persist&gt;</code> to auto-save field values to <code>localStorage</code> or <code>sessionStorage</code>. Clears on submit.</p>',
            '      <p class="lead">Wrap a form (or any container) with <code>&lt;velin-persist&gt;</code> to auto-save field values to <code>localStorage</code> or <code>sessionStorage</code>. '
            'Helps meet WCAG 2.2 <strong>3.3.7 Redundant Entry</strong> when users return to a flow. Clears stored data on submit. '
            'Listed in <code>core/a11y/component-contracts.json</code> (framework audit: pass).</p>',
        ),
    )

    # Upgrading
    patch_file(
        "getting-started/upgrading.html",
        (
            "        <li><strong>Components:</strong> all 35 web components pass <code>core/a11y/component-contracts.json</code>; run <code>npm run test:a11y:coverage</code>.</li>",
            "        <li><strong>Components:</strong> 36 web components in <code>core/a11y/component-contracts.json</code> (all pass); run <code>npm run test:a11y:coverage</code> in the framework repo.</li>",
        ),
    )

    # Velin meta guide - read file and patch
    meta_path = DOCS / "guides/velin-meta.html"
    if meta_path.is_file():
        t = meta_path.read_text(encoding="utf-8")
        ins = (
            '      <h2 id="agent-json">velin-agent.json</h2>\n'
            '      <p>Fields include <code>schemaVersion</code>, <code>mime</code>, <code>framework</code>, '
            '<code>packageExports</code>, <code>components</code> (tags, count, loaderTags, legacyAliases, helpers), '
            '<code>attributes</code>, <code>cli</code>, <code>a11y</code>, <code>searchIndex</code>, and <code>documentation</code>.</p>\n'
            '      <p><strong>Component inventory (0.9.0 audit):</strong> <code>components.tags</code> lists <strong>36 canonical</strong> custom elements; '
            '<code>components.loaderCount</code> is <strong>38</strong> (includes deprecated <code>velin-tooltip-wc</code> and <code>velin-stepper-wc</code>); '
            '<code>components.legacyAliases</code> documents those aliases; <code>components.helpers</code> lists JS modules '
            '<code>velin-flip</code>, <code>velin-haptic</code>, <code>velin-reveal</code> (not custom elements). '
            'Fields include <code>schemaVersion</code>, <code>mime</code>, <code>framework</code>, '
            '<code>packageExports</code>, <code>components</code>, <code>attributes</code>, <code>cli</code>, <code>a11y</code>, <code>searchIndex</code>, and <code>documentation</code>.</p>\n'
            '      <h2 id="conventions">Conventions</h2>\n'
        )
        if ins not in t:
            t = t.replace(
                '      <h2 id="conventions">Conventions</h2>',
                ins,
                1,
            )
            meta_path.write_text(t, encoding="utf-8")
            print("patched guides/velin-meta.html")

    # Repo tools
    repo_path = DOCS / "extend/repo-tools.html"
    if repo_path.is_file():
        t = repo_path.read_text(encoding="utf-8")
        add = (
            '      <h2 id="e2e">End-to-end tests (Playwright)</h2>\n'
            '      <table class="velin-table"><thead><tr><th>Command</th><th>Description</th></tr></thead><tbody>\n'
            '        <tr><td><code>npm run test:e2e</code></td><td>Cross-browser WC smoke (Chromium, Firefox, WebKit)</td></tr>\n'
            '        <tr><td><code>npm run test:e2e:chromium</code></td><td>Chromium only (faster local check)</td></tr>\n'
            '        <tr><td><code>npm run test:a11y:coverage</code></td><td>Component contract coverage (36/36)</td></tr>\n'
            '      </tbody></table>\n'
            '      <p>Requires <code>npm run build</code> first. Framework path: <code>tests/e2e/</code>.</p>\n\n'
        )
        if "<h2 id=\"e2e\">" not in t:
            t = t.replace(
                '      <h2 id="relation-cli">Relation to the CLI</h2>',
                add + '      <h2 id="relation-cli">Relation to the CLI</h2>',
                1,
            )
            t = t.replace(
                '<li><a href="#relation-cli">CLI</a></li></ul></aside>',
                '<li><a href="#e2e">E2E tests</a></li><li><a href="#relation-cli">CLI</a></li></ul></aside>',
                1,
            )
            repo_path.write_text(t, encoding="utf-8")
            print("patched extend/repo-tools.html")

    # Reboot / content
    reboot = DOCS / "content/reboot.html"
    if reboot.is_file():
        t = reboot.read_text(encoding="utf-8")
        if "wc-placeholder" not in t:
            t = t.replace(
                "<h1>Reboot</h1>",
                "<h1>Reboot</h1>\n"
                "      <p class=\"lead\">VelinStyle includes a modern CSS reset and, since 0.9.0, <code>src/base/wc-placeholder.css</code> to reduce layout shift while custom elements load.</p>",
                1,
            )
            reboot.write_text(t, encoding="utf-8")
            print("patched content/reboot.html")

    print("Done.")


if __name__ == "__main__":
    main()
